name: "Pull Request Checks"

on:
  pull_request:

jobs:
  ##
  # validation
  ##

  validate_pr_title:
    name: "Validate PR Title"
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🦫 Setup Golang"
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
      - name: "📥 Get PR Title"
        id: get_pr_title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return data.title;
      - name: "✅ Validate"
        run: |
          make init
          echo "${{ steps.get_pr_title.outputs.result }}" | commitlint lint

  ##
  # build
  ##

  build:
    name: "Build"
    needs: [validate_pr_title]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🦫 Install Go dependencies"
        uses: ./.github/actions/use-go-dependencies
      - name: "📦 Install Node dependencies"
        uses: ./.github/actions/use-pnpm-dependencies
      - name: "🏗️ Build"
        run: ./scripts/build.sh
